# Generated by Django 3.2.14 on 2023-04-14 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='quillpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quillpost',
            name='title',
            field=models.TextField(default='Hello world', max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quillpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
