# Generated by Django 3.2.14 on 2023-04-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230414_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='quillpost',
            name='description',
            field=models.TextField(default='This is a sample description', max_length=240),
            preserve_default=False,
        ),
    ]
