# Generated by Django 3.2.14 on 2023-04-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_quillpost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quillpost',
            name='description',
            field=models.TextField(max_length=180),
        ),
        migrations.AlterField(
            model_name='quillpost',
            name='title',
            field=models.TextField(max_length=180),
        ),
    ]
