# Generated by Django 3.2.14 on 2023-04-14 09:53

from django.db import migrations, models
import django.utils.timezone
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_quillpost_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuillPost',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=django_quill.fields.QuillField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='desc', max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=180),
        ),
    ]
