# Generated by Django 3.2.14 on 2023-06-06 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialcheckin',
            name='bowel_frequency',
            field=models.CharField(choices=[('Multiple times per day', 'Multiple times per day'), ('Once a day', 'Once a day'), ('Every other day', 'Every other day'), ('Infrequent', 'Infrequent')], default=1, max_length=400, verbose_name='How frequent were your bowl movements this week?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initialcheckin',
            name='contraceptive',
            field=models.CharField(default=1, max_length=400, verbose_name='Are you currently taking/using a contraceptive? If yes, please state which type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initialcheckin',
            name='digestive_describe',
            field=models.CharField(default=1, max_length=400, verbose_name='Describe your digestive issues  or write "n/a" if you did not have any'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initialcheckin',
            name='digestive_issues',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unsure', 'Unsure')], default=1, max_length=400, verbose_name='Have you had any digestive issues this week?i.e. gas, bloating, diarrhoea, etc.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initialcheckin',
            name='energy',
            field=models.CharField(choices=[('Very Low', 'Very Low'), ('Low', 'Low'), ('Average', 'Average'), ('High', 'High'), ('Very High', 'Very High')], default=1, max_length=400, verbose_name='How was your energy this week?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initialcheckin',
            name='extra',
            field=models.CharField(default=1, max_length=400, verbose_name='Anything more you would like to briefly comment on or share about yourself?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initialcheckin',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Height (in cm)'),
        ),
        migrations.AddField(
            model_name='initialcheckin',
            name='hip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Hip (in cm)'),
        ),
        migrations.AddField(
            model_name='initialcheckin',
            name='left_bicep',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Left bicep (in cm)'),
        ),
        migrations.AddField(
            model_name='initialcheckin',
            name='left_quad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Left quad (in cm)'),
        ),
        migrations.AddField(
            model_name='initialcheckin',
            name='medication',
            field=models.CharField(default=1, max_length=400, verbose_name='Are you currently on any medications? if yes, please give details'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initialcheckin',
            name='neck',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Neck (in cm)'),
        ),
        migrations.AddField(
            model_name='initialcheckin',
            name='period_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='When is your next period due?'),
        ),
        migrations.AddField(
            model_name='initialcheckin',
            name='sleep',
            field=models.CharField(choices=[('Very Poor', 'Very Poor'), ('Below Average', 'Below Average'), ('Average', 'Average'), ('Good', 'Good'), ('Very Good', 'Very Good')], default=1, max_length=400, verbose_name='How was your sleep this week?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initialcheckin',
            name='stress',
            field=models.CharField(choices=[('Not Stressed', 'Not Stressed'), ('Some Stress', 'Some Stress'), ('Average Stress', 'Average Stress'), ('Quite Stressed', 'Quite Stressed'), ('Very Stressed', 'Very Stressed')], default=1, max_length=400, verbose_name='How were your stress levels this week?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initialcheckin',
            name='waist',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Waist (in cm)'),
        ),
    ]
