# Generated by Django 3.2.14 on 2023-04-11 13:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(auto_now=True, default=datetime.datetime(2023, 4, 11, 13, 31, 52, 715728, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
