# Generated by Django 3.2.14 on 2023-04-11 13:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_journal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 11, 13, 33, 43, 10326, tzinfo=utc)),
        ),
    ]
