# Generated by Django 3.2.14 on 2023-04-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_journal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='carbohydrate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='fat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='journal',
            name='protein',
            field=models.IntegerField(),
        ),
    ]
