# Generated by Django 3.2.14 on 2023-04-12 07:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='period_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 12, 7, 49, 5, 916846, tzinfo=utc), verbose_name='When is your next period due?'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('protein', models.IntegerField()),
                ('carbohydrate', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('hydration', models.IntegerField()),
                ('suplements', models.CharField(max_length=400)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
