# Generated by Django 3.2.14 on 2023-04-12 08:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20230412_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='period_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 12, 8, 21, 27, 219114, tzinfo=utc), verbose_name='When is your next period due?'),
        ),
        migrations.CreateModel(
            name='InitialCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(auto_now_add=True)),
                ('starting_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goal_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('comp_date', models.DateField(verbose_name='Competition Date (YYYY-MM-DD)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_checkin', to='orders.order')),
            ],
        ),
    ]
