# Generated by Django 3.2.14 on 2023-04-13 11:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0011_2_7'),
        ('orders', '0008_auto_20230412_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-purchase_date']},
        ),
        migrations.AlterField(
            model_name='checkin',
            name='period_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 13, 11, 27, 31, 630162, tzinfo=utc), verbose_name='When is your next period due?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djstripe.product'),
        ),
    ]
