# Generated by Django 3.2.14 on 2023-04-13 12:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20230413_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='period_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 13, 12, 6, 24, 567039, tzinfo=utc), verbose_name='When is your next period due?'),
        ),
    ]
