# Generated by Django 3.2.14 on 2023-04-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20230413_0913'),
        ('orders', '0011_alter_checkin_period_date'),
    ]

    operations = [
    ]
