# Generated by Django 3.2.14 on 2023-04-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('slug', models.SlugField()),
                ('thumbnail', models.ImageField(null=True, upload_to='product_thumbnails')),
                ('description', models.CharField(max_length=250)),
                ('stripe_price_id', models.CharField(max_length=50)),
                ('mode', models.CharField(choices=[('payment', 'payment'), ('subscription', 'subscription')], max_length=250)),
                ('frequency', models.CharField(blank=True, choices=[('/month', '/month'), ('/week', '/week')], max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
